import {
    Activity,
    AlarmClock,
    BadgeCheck,
    Ban,
    Bell,
    BookOpen,
    Brain,
    BriefcaseBusiness,
    CalendarClock,
    CalendarDays,
    CheckCircle2,
    CircleCheck,
    CircleDot,
    CirclePause,
    CircleSlash,
    Clock3,
    Coffee,
    Contact,
    Focus,
    GraduationCap,
    Headphones,
    Heart,
    Hourglass,
    Info,
    Laptop,
    Lightbulb,
    Lock,
    MessageCircle,
    MessagesSquare,
    Moon,
    Phone,
    Presentation,
    RefreshCw,
    Route,
    Shield,
    ShieldCheck,
    Sparkles,
    Star,
    Sun,
    Timer,
    TriangleAlert,
    UserCheck,
    UserRoundCheck,
    Users,
    Utensils,
    Workflow,
    Wrench,
    Zap,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

export const agentStatusIconMap: Record<string, LucideIcon> = {
    activity: Activity,
    'alarm-clock': AlarmClock,
    'badge-check': BadgeCheck,
    ban: Ban,
    bell: Bell,
    'book-open': BookOpen,
    brain: Brain,
    'briefcase-business': BriefcaseBusiness,
    'calendar-clock': CalendarClock,
    'calendar-days': CalendarDays,
    'check-circle': CheckCircle2,
    'circle-check': CircleCheck,
    'circle-dot': CircleDot,
    'circle-pause': CirclePause,
    'circle-slash': CircleSlash,
    clock: Clock3,
    coffee: Coffee,
    contact: Contact,
    focus: Focus,
    'graduation-cap': GraduationCap,
    headphones: Headphones,
    heart: Heart,
    hourglass: Hourglass,
    info: Info,
    laptop: Laptop,
    lightbulb: Lightbulb,
    lock: Lock,
    'message-circle': MessageCircle,
    'messages-square': MessagesSquare,
    moon: Moon,
    phone: Phone,
    presentation: Presentation,
    'refresh-cw': RefreshCw,
    route: Route,
    shield: Shield,
    'shield-check': ShieldCheck,
    sparkles: Sparkles,
    star: Star,
    sun: Sun,
    timer: Timer,
    'triangle-alert': TriangleAlert,
    'user-check': UserCheck,
    'user-clock': Clock3,
    'user-round-check': UserRoundCheck,
    users: Users,
    utensils: Utensils,
    workflow: Workflow,
    wrench: Wrench,
    zap: Zap,
}

export function resolveAgentStatusIcon(icon: string): LucideIcon {
    return agentStatusIconMap[icon] ?? Activity
}

export function formatAgentStatusIconName(icon: string): string {
    return icon
        .replace(/[-_]+/g, ' ')
        .trim()
        .split(/\s+/)
        .map(
            (part) =>
                part.charAt(0).toUpperCase() +
                part.slice(1),
        )
        .join(' ')
}
