import { Head, Link, useForm } from '@inertiajs/react'
import { route } from 'ziggy-js'

import InputError from '@/Components/InputError'
import { Button } from '@/Components/ui/button'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/Components/ui/select'
import AdminLayout from '@/Layouts/AdminLayout'

type Definition = { type: string; name: string; available: boolean; unavailable_reason?: string | null }
type Connection = { id: number; name: string; type: string; is_enabled: boolean; deleted_at: string | null }
type Configuration = { id: number; name: string; driver: string; infrastructure_connection_id: number; is_enabled: boolean }
export default function Form({ configuration, definitions, connections }: { configuration: Configuration | null; definitions: Definition[]; connections: Connection[] }) {
    const form = useForm({ name: configuration?.name ?? '', driver: configuration?.driver ?? 'reverb', infrastructure_connection_id: configuration?.infrastructure_connection_id ?? 0, configuration: {}, is_enabled: configuration?.is_enabled ?? true })
    const allowedConnections = connections.filter((item) => item.type === form.data.driver || item.id === configuration?.infrastructure_connection_id)
    const submit = () => configuration ? form.put(route('admin.system.broadcasting.update', { configuration: configuration.id })) : form.post(route('admin.system.broadcasting.store'))
    return <AdminLayout title={configuration ? 'Edit Real-time profile' : 'New Real-time profile'}><Head title="Real-time profile" /><div className="mx-auto max-w-3xl rounded-[28px] border bg-white p-6 shadow-sm"><h1 className="text-xl font-semibold">{configuration ? 'Edit Real-time profile' : 'New Real-time profile'}</h1><p className="mt-1 text-sm text-gray-500">Secrets and endpoint settings remain owned by the selected Infrastructure Connection.</p><div className="mt-6 space-y-5"><label className="block text-sm font-medium">Name<input className="mt-2 w-full rounded-xl border px-3 py-2" value={form.data.name} onChange={(event) => form.setData('name', event.target.value)} /></label><InputError message={form.errors.name} /><div><p className="text-sm font-medium">Provider</p><Select disabled={Boolean(configuration)} value={form.data.driver} onValueChange={(value) => { form.setData('driver', value); form.setData('infrastructure_connection_id', 0) }}><SelectTrigger className="mt-2 w-full"><SelectValue /></SelectTrigger><SelectContent>{definitions.map((item) => <SelectItem key={item.type} disabled={!item.available} value={item.type}>{item.name}{item.available ? '' : ' (unavailable)'}</SelectItem>)}</SelectContent></Select><InputError message={form.errors.driver} /></div><div><p className="text-sm font-medium">Infrastructure connection</p><Select value={String(form.data.infrastructure_connection_id || '')} onValueChange={(value) => form.setData('infrastructure_connection_id', Number(value))}><SelectTrigger className="mt-2 w-full"><SelectValue placeholder="Select connection" /></SelectTrigger><SelectContent>{allowedConnections.map((item) => <SelectItem key={item.id} disabled={!item.is_enabled || Boolean(item.deleted_at)} value={String(item.id)}>{item.name}{item.deleted_at ? ' (archived)' : !item.is_enabled ? ' (disabled)' : ''}</SelectItem>)}</SelectContent></Select><InputError message={form.errors.infrastructure_connection_id} /></div><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={form.data.is_enabled} onChange={(event) => form.setData('is_enabled', event.target.checked)} />Enabled</label><div className="flex justify-end gap-3"><Button variant="outline" asChild><Link href={route('admin.system.broadcasting.index')}>Cancel</Link></Button><Button disabled={form.processing} onClick={submit}>Save</Button></div></div></div></AdminLayout>
}
