<?php

return [
    'sections' => [
        'sections.users' => [
            ['icon' => 'bi-person-fill', 'label' => 'users.agents', 'route' => 'admin.agents.index'],
            ['icon' => 'bi-person-check-fill', 'label' => 'users.roles'],
            ['icon' => 'bi-diagram-3-fill', 'label' => 'users.departments'],
            ['icon' => 'bi-people-fill', 'label' => 'users.teams', 'route' => 'admin.teams.index'],
        ],
        'sections.email' => [
            ['icon' => 'bi-envelope-fill', 'label' => 'email.settings'],
            ['icon' => 'bi-slash-circle-fill', 'label' => 'email.breaklines'],
            ['icon' => 'bi-heart-pulse-fill', 'label' => 'email.diagnostics'],
            ['icon' => 'bi-fingerprint', 'label' => 'email.oauth'],
        ],
        'sections.drivers' => [
            ['icon' => 'bi-arrow-repeat', 'label' => 'drivers.queues'],
            ['icon' => 'bi-cloud-fill', 'label' => 'drivers.cache'],
            ['icon' => 'bi-lightning-charge-fill', 'label' => 'drivers.websockets'],
            ['icon' => 'bi-search', 'label' => 'drivers.search'],
        ],
        'sections.manage' => [
            ['icon' => 'bi-repeat', 'label' => 'manage.automation'],
            ['icon' => 'bi-file-earmark-text-fill', 'label' => 'manage.help_topics'],
            ['icon' => 'bi-clock', 'label' => 'manage.sla_plans'],
            ['icon' => 'bi-calendar-date', 'label' => 'manage.business_hours'],
            ['icon' => 'bi-file-earmark', 'label' => 'manage.forms'],
            ['icon' => 'bi-journal-text', 'label' => 'manage.ticket_fields'],
            ['icon' => 'bi-diagram-2', 'label' => 'manage.approval_workflow'],
            ['icon' => 'bi-asterisk', 'label' => 'manage.priority'],
            ['icon' => 'bi-list-check', 'label' => 'manage.ticket_types'],
            ['icon' => 'bi-book-half', 'label' => 'manage.widgets'],
            ['icon' => 'bi-file-earmark-check', 'label' => 'manage.daily_report'],
            ['icon' => 'bi-grid-1x2-fill', 'label' => 'manage.admin_panel'],
        ],
        'sections.tickets' => [
            ['icon' => 'bi-file-earmark-post', 'label' => 'tickets.settings'],
            ['icon' => 'bi-tag', 'label' => 'tickets.status'],
            ['icon' => 'bi-lightning-charge-fill', 'label' => 'tickets.labels'],
            ['icon' => 'bi-stars', 'label' => 'tickets.ratings'],
            ['icon' => 'bi-diagram-3', 'label' => 'tickets.workflow'],
            ['icon' => 'bi-tags', 'label' => 'tickets.tags'],
            ['icon' => 'bi-check-square', 'label' => 'tickets.auto_assignment'],
            ['icon' => 'bi-database', 'label' => 'tickets.source'],
            ['icon' => 'bi-copy', 'label' => 'tickets.recurring'],
            ['icon' => 'bi-map', 'label' => 'tickets.location'],
            ['icon' => 'bi-book', 'label' => 'tickets.template'],
            ['icon' => 'bi-filetype-pdf', 'label' => 'tickets.pdf_template'],
        ],
        'sections.settings' => [
            ['icon' => 'bi-building', 'label' => 'settings.company'],
            ['icon' => 'bi-laptop', 'label' => 'settings.system'],
            ['icon' => 'bi-person', 'label' => 'settings.contact'],
            ['icon' => 'bi-globe', 'label' => 'settings.social_login'],
            ['icon' => 'bi-translate', 'label' => 'settings.language'],
            ['icon' => 'bi-hourglass', 'label' => 'settings.cron'],
            ['icon' => 'bi-safe', 'label' => 'settings.security'],
            ['icon' => 'bi-folder', 'label' => 'settings.filesystem'],
            ['icon' => 'bi-database-fill-gear', 'label' => 'settings.backup'],
            ['icon' => 'bi-link-45deg', 'label' => 'settings.social_widget'],
            ['icon' => 'bi-folder-symlink', 'label' => 'settings.webhook'],
            ['icon' => 'bi-download', 'label' => 'settings.user_import'],
            ['icon' => 'bi-arrow-repeat', 'label' => 'settings.recaptcha'],
            ['icon' => 'bi-box-arrow-up-right', 'label' => 'settings.login_log'],
            ['icon' => 'bi-funnel', 'label' => 'settings.customer_filter'],
        ],
        'sections.addons' => [
            ['icon' => 'bi-plug', 'label' => 'addons.plugins'],
            ['icon' => 'bi-link', 'label' => 'addons.modules'],
        ],
        'sections.developer_settings' => [
            ['icon' => 'bi-gear-wide-connected', 'label' => 'developer.api'],
            ['icon' => 'bi-cloud', 'label' => 'developer.third_party_apps'],
            ['icon' => 'bi-box-arrow-in-right', 'label' => 'developer.saml_integration'],
            ['icon' => 'bi-key', 'label' => 'developer.personal_access_tokens'],
            ['icon' => 'bi-lock-fill', 'label' => 'developer.oauth_app'],
            ['icon' => 'bi-display', 'label' => 'developer.iframe_injection'],
        ],
        'sections.notifications' => [
            ['icon' => 'bi-file-earmark-break', 'label' => 'notifications.template_management'],
            ['icon' => 'bi-mailbox', 'label' => 'notifications.notification_management'],
            ['icon' => 'bi-bell', 'label' => 'notifications.in_app_log'],
        ],
        'sections.billing' => [
            ['icon' => 'bi-wrench', 'label' => 'billing.options'],
            ['icon' => 'bi-bag', 'label' => 'billing.package'],
            ['icon' => 'bi-cash', 'label' => 'billing.payment_gateway'],
        ],
        'sections.health_check' => [
            ['icon' => 'bi-heart-pulse', 'label' => 'health_check.check'],
            ['icon' => 'bi-bell', 'label' => 'health_check.alerts'],
            ['icon' => 'bi-bug-fill', 'label' => 'health_check.debug_options'],
            ['icon' => 'bi-clock-history', 'label' => 'health_check.system_logs'],
            ['icon' => 'bi-box-arrow-in-right', 'label' => 'health_check.activity_logs'],
        ],
        'sections.attachment_scanner' => [
            ['icon' => 'bi-shield-lock', 'label' => 'attachment_scanner.scanner_list'],
        ],
        'sections.additional_configs' => [
            ['icon' => 'bi-stopwatch-fill', 'label' => 'additional_configs.time_tracking'],
            ['icon' => 'bi-filetype-css', 'label' => 'additional_configs.custom_css'],
            ['icon' => 'bi-filetype-js', 'label' => 'additional_configs.custom_js'],
            ['icon' => 'bi-facebook', 'label' => 'additional_configs.facebook'],
            ['icon' => 'bi-bar-chart-line', 'label' => 'additional_configs.lime_survey'],
            ['icon' => 'bi-chat-dots', 'label' => 'additional_configs.slack'],
            ['icon' => 'bi-twitter-x', 'label' => 'additional_configs.twitter_x'],
            ['icon' => 'bi-whatsapp', 'label' => 'additional_configs.whatsapp'],
            ['icon' => 'bi-x-octagon-fill', 'label' => 'additional_configs.zendesk'],
        ],
    ],
];
